<?php
echo <<<HTML
<footer>
    <section class="footer-content">
        <!-- Credits section -->
        <div class="credits">
            <h3 class="section-title">CREDITS</h3>
            <div><h4><a href="mailto:103606281@student.swin.edu.au" class="name-link">Wing</a></h4></div>
            <div><h4><a href="mailto:104226143@student.swin.edu.au" class="name-link">Finn</a></h4></div>
            <div><h4><a href="mailto:104757410@student.swin.edu.au" class="name-link">Alex</a></h4></div>
        </div>

        <!-- Contact section -->
        <div class="contact">
            <h4 class="section-title">Contact Us</h4>
            <strong>Email: </strong><a href="mailto:swift.outsource.it@gmail.com" class="name-link">swift.outsource.it@gmail.com</a>
            <p><strong class="label">Contact number: </strong><a href="tel:0450917043" class="name-link">0450 917 043</a></p>
            <h5>&copy; 2023 <em>Team Swift</em></h5>
        </div>
        
        <!-- Map section -->
        <div class="map">
            <p><span class="section-title"><strong>Location:</strong></span> <a href="https://goo.gl/maps/a4J2ZC3qF3CftMJQA"  class="name-link" target="_blank" rel="noopener noreferrer">456 Bourke St, Melbourne VIC 3000</a></p>
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1575.9670134905195!2d144.95972163575175!3d-37.81501424657349!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x6ad65d4b38985dcf%3A0xeabf0996017c8237!2s456%20Bourke%20St%2C%20Melbourne%20VIC%203000!5e0!3m2!1sen!2sau!4v1694263175011!5m2!1sen!2sau" width="300" height="225" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
        </div>
    </section>
</footer>
HTML;
?>
